# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrsToolchain < Formula
  desc "CRS developer's utility belt"
  homepage "https://github.com/coreruleset/crs-toolchain"
  version "2.8.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/coreruleset/crs-toolchain/releases/download/v2.8.0/crs-toolchain_2.8.0_darwin_amd64.tar.gz"
      sha256 "ed3d7e33da7840a226a5da8fccc56ce26dcda4c543fae518ce67b60d2c53b8de"

      define_method(:install) do
        bin.install "crs-toolchain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/coreruleset/crs-toolchain/releases/download/v2.8.0/crs-toolchain_2.8.0_darwin_arm64.tar.gz"
      sha256 "8b6bdb3428f377fadb41c864b7bce6a975a526189863312da6a765dbc6c982be"

      define_method(:install) do
        bin.install "crs-toolchain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreruleset/crs-toolchain/releases/download/v2.8.0/crs-toolchain_2.8.0_linux_amd64.tar.gz"
      sha256 "ac9baefe8a9775e2b56f466ea042043a5d8824e814a9764e864bf9e3e3474e62"
      define_method(:install) do
        bin.install "crs-toolchain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreruleset/crs-toolchain/releases/download/v2.8.0/crs-toolchain_2.8.0_linux_arm64.tar.gz"
      sha256 "8cea86303f53d9e41cab3ef25946b5293a3ec7a1a6c760de9be40c546f8126b9"
      define_method(:install) do
        bin.install "crs-toolchain"
      end
    end
  end
end
