# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoFtw < Formula
  desc "Framework for Testing WAFs - Go version"
  homepage "https://github.com/coreruleset/go-ftw"
  version "2.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/coreruleset/go-ftw/releases/download/v2.5.0/ftw_2.5.0_darwin_amd64.tar.gz"
      sha256 "f10fe3551dab40c32ddae0ece53bdfe24120aaa0e6cefc46e7c1b3555897f3fe"

      define_method(:install) do
        bin.install "ftw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/coreruleset/go-ftw/releases/download/v2.5.0/ftw_2.5.0_darwin_arm64.tar.gz"
      sha256 "2f15951d6cee1ffba88a1ab4adae046be0086177b08355c982a4d1c6458cf66d"

      define_method(:install) do
        bin.install "ftw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreruleset/go-ftw/releases/download/v2.5.0/ftw_2.5.0_linux_amd64.tar.gz"
      sha256 "7fcb605873a40e3f48e4f9653b884177e1f5562772e1b8b01a1c574354f0fb39"
      define_method(:install) do
        bin.install "ftw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coreruleset/go-ftw/releases/download/v2.5.0/ftw_2.5.0_linux_arm64.tar.gz"
      sha256 "ac7f0e3d0fb39cbede8acee264df03735ff10ab66b1009bd004dd13261616d2b"
      define_method(:install) do
        bin.install "ftw"
      end
    end
  end
end
